language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
       - pip install django==1.3
script: 
- pip install --upgrade pip
- pip freeze 
- python manage.py test customtags_tests
